apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

components:
  - git@github.com:armory/spinnaker-kustomize-patches.git/core/base
  - git@github.com:armory/spinnaker-kustomize-patches.git/targets/kubernetes/default
  # TODO needs docs upstream
  - git@github.com:armory/spinnaker-kustomize-patches.git/core/persistence/s3?ref=feat/add-s3-persistance-component
  - git@github.com:armory/spinnaker-kustomize-patches.git/artifacts/docker/ecr?ref=feat/add-dockerhub-component

patchesStrategicMerge:
  - ./version.yml
  - ./s3-bucket.yml
  #- ./load-balancer.yml

patches:
  - target:
      kind: SpinnakerService
    path: ./switch-to-oss.yml
  - target:
      kind: SpinnakerService
    path: ./ecr-registry.yml
