apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

components:
  - https://github.com/armory/spinnaker-kustomize-patches.git/core/base
  - https://github.com/armory/spinnaker-kustomize-patches.git/targets/kubernetes/default
  - https://github.com/armory/spinnaker-kustomize-patches.git/core/persistence/s3
    # TODO: needs docs upstream
  - https://github.com/armory/spinnaker-kustomize-patches.git/artifacts/docker/ecr?ref=feat/add-dockerhub-component

patchesStrategicMerge:
  - ./version.yml
  - ./s3-bucket.yml
  - ./gitrepo.yml
  - ./load-balancer.yml

patches:
  - target:
      kind: SpinnakerService
    path: ./switch-to-oss.yml
  - target:
      kind: SpinnakerService
    path: ./ecr-registry.yml
