apiVersion: v1
kind: Service
metadata:
  name: &app-name hello-world
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: *app-name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app-name hello-world
spec:
  selector:
    matchLabels:
      app: *app-name
  replicas: 3
  template:
    metadata:
      labels:
        app: *app-name
    spec:
      containers:
        - name: nginx
          image: ${parameters["repo_name"]}:${trigger['tag']}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
